### ISSUE TITLE
Sync Broken After Udon Network Update

### ISSUE THREAD

**Issue by ShiguriVR** [VrcUdon/UdonVideoplayer#2]
I'm pretty sure the network update to Udon broke the player somehow. Videos work locally but is no longer synced.
This is after updating Udon and USharp to the latest versions, and when I downgraded both it started working again.

Just thought I'd report it.

**Comment by ChildoftheBeast** [comment]
i'll make sure to update our sdk used for testing and confirm, seems to be fine if a pre-UNU SDK is used.

**Comment by ChildoftheBeast** [comment]
@ShiguriVR 
it seems to be working fine with the newist sdk, can i get the World ID you were using? you can either post it here or DM it to me through Discord

http://discord.gg/dpuxmxr

**Comment by ChildoftheBeast** [comment]
Closing, seems to be fixed and/or cant replicate
comment again or DM me via discord if you're still seeing issues
